### ISSUE TITLE
add a status command

### ISSUE THREAD

**Issue by johnpapa** [vsls-contrib/chat#20]
It would be awesome to add a command for `/live status`. I envision this would show whether a current share is active and show the link.

Why? I entered `/live share` and the link was sent. I close the slack window as i put it in the wrong channel. Go back in and perhaps i cant find the link. a simple status command could help show this.

**Comment by lostintangent** [comment]
@johnpapa Or maybe “/live share” could detect that you’re already in a Live Share session and simply re-send the join URL to the active channel/thread?

**Comment by arjun27** [comment]
Closing this since the Live Share's tree views have been implemented.  Additionally, `/live share` in a new channel sends the same join URL.

Feel free to re-open if I missed something :)
