### ISSUE TITLE
[vscode] [discord] Invalid token

### ISSUE THREAD

**Issue by karu007** [vsls-contrib/chat#244]
- Extension Version: 0.7.3
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.1

**Comment by arjun27** [comment]
Hey @karu007 , thanks for reporting this. Could you share more info on how this happened? The token mechanism as detailed in the doc should work - please let me know if there's anything missing in the doc

Doc link: https://github.com/karigari/vscode-chat/blob/master/docs/DISCORD.md

**Comment by arjun27** [comment]
Discord auth is unofficial and not recommended
