### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by wacsintegra** [vsls-contrib/chat#268]
Sign in with slack failed: access_denied

- Extension Version: 0.8.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.29.1

Confirmed same issue occurs while confirming login prior and post to running the connection from Visual Code.

**Comment by arjun27** [comment]
thanks @wacsintegra. we have compiled a list of potential problems/solutions to this in this doc: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

could you tell me if any of these apply to you? if not, I'd love to investigate further and find a fix for this. thanks!

**Comment by wacsintegra** [comment]
@arjun27 Thank you for the follow up. We have to add the app to our account in Slack, we will do so once the review process at Slack has completed! 
Cheers sir!

**Comment by arjun27** [comment]
thanks @wacsintegra. we're tracking the slack review process in #78. unfortunately we haven't made much progress there yet, but I would recommend subscribing to that issue. is there anything in particular that concerns you and I could help you with, before we start the review process?

**Comment by wacsintegra** [comment]
We have a rule in place as an org to not install non-reviewed components and we currently do not have sandbox environment to test or setup and confirm.
