### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by kurtinlane** [vsls-contrib/chat#274]
Sign in with slack failed: access_denied

- Extension Version: 0.8.2
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.29.1

**Comment by arjun27** [comment]
Thanks @kurtinlane. We have compiled a list of potential problems/solutions to this in this doc: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md

Could you tell me if any of these apply to you? If not, I'd love to investigate further and find a fix for this. Thanks!
