### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by temitope** [vsls-contrib/chat#281]
we need to be an admin of the workspace to install slack for vscode plugin locally? When i try to install im getting this error,

Sign in with slack failed: access_denied

- Extension Version: 0.9.0
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.28.2

**Comment by arjun27** [comment]
Please see https://github.com/vsls-contrib/chat/blob/master/docs/SLACK.md
