### ISSUE TITLE
[vscode] Unable to access keychain (Linux)

### ISSUE THREAD

**Issue by denis-onder** [vsls-contrib/chat#285]
Error: The name org.freedesktop.secrets was not provided by any .service files

- Extension Version: 0.9.0
- OS Version: Linux x64 4.19.12-2-MANJARO
- VSCode version: 1.30.1

**Comment by tibotiber** [comment]
duplicate #277

**Comment by arjun27** [comment]
Thanks for reporting this, @DennisOnder.

I don't think this is a duplicate of #277, since the error string and OS are different. I'll investigate further

**Comment by arjun27** [comment]
possibly related to #289

**Comment by arjun27** [comment]
Hi @DennisOnder, can you try installing extra/gnome-keyring in your system? That fixed a similar issue in #329

**Comment by arjun27** [comment]
Follow #325 for fix. Closing as duplicate
