### ISSUE TITLE
[vscode] Unable to access keychain (Linux)

### ISSUE THREAD

**Issue by cuppajoeman** [vsls-contrib/chat#287]
Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

- Extension Version: 0.9.2
- OS Version: Linux x64 4.19.12-arch1-1-ARCH
- VSCode version: 1.30.1

**Comment by arjun27** [comment]
possibly related to #289. tracking fix for keychain issues in Linux over there.

**Comment by arjun27** [comment]
Hi @Ajaymeledath, can you try installing extra/gnome-keyring in your system? That fixed a similar issue in #329

**Comment by arjun27** [comment]
Follow #325 for fix. Closing as duplicate
