### ISSUE TITLE
[vscode] Unable to access keychain (Linux)

### ISSUE THREAD

**Issue by pahosler** [vsls-contrib/chat#289]
Error: Unknown or unsupported transport “disabled” for address “disabled:”

- Extension Version: 0.9.2
- OS Version: Linux x64 4.18.0-13-generic
- VSCode version: 1.30.1

**Comment by pahosler** [comment]
when trying to sign in to discord. Apologies for not being more specific

**Comment by arjun27** [comment]
thanks for reporting @pahosler. we're facing some issues accessing the keychain on some linux machines. which linux distro are you on?

**Comment by pahosler** [comment]
Ubuntu 18.10
i3wm (if that makes any difference, I expect not)
Linux dot 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by arjun27** [comment]
thanks! it looks like we need a better way to store credentials on linux. I'm not sure what the right answer is, but I'm hoping to fix this soon. do you use VS Live Share? does your credential store have Live Share credentials?

**Comment by smug-haus** [comment]
Hey @arjun27 there's no need to look for a better way to store creds.

VS Code uses Node's `keytar` package to access the key store on various platforms. 

Per the [documentation](https://www.npmjs.com/package/keytar) This issue can be resolved by installing `libsecret-1-dev`:

**Debian/Ubuntu:** `sudo apt-get install libsecret-1-dev`
**Red Hat-based:** `sudo yum install libsecret-devel`
**Arch Linux:** `sudo pacman -S libsecret`

**Comment by arjun27** [comment]
Follow #325 for fix. Closing as duplicate
