### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by VishnuBaliga** [vsls-contrib/chat#290]
Sign in with slack failed: access_denied

- Extension Version: 0.9.2
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.30.1

**Comment by arjun27** [comment]
thanks for reporting this @VishnuBaliga. were any of the suggestions in our docs helpful? link: https://github.com/karigari/vscode-chat/blob/master/docs/SLACK.md
