### ISSUE TITLE
[vscode] [discord] Discord Token

### ISSUE THREAD

**Issue by Kogam22** [vsls-contrib/chat#314]
I don't understand how to get the token. Can you check this issue I created on the same topic on discord-api-docs repo and tell me where I went wrong ?

https://github.com/discordapp/discord-api-docs/issues/847

**Comment by SinisterRectus** [comment]
Discord does not support user account automation outside of their OAuth2 API . Additionally, submitting user tokens outside of their client is a security risk. For these reasons, they removed the ability to access user tokens via `localStorage`.

**Comment by Kogam22** [comment]
@SinisterRectus Then . . . Is this extension useless for discord ?

**Comment by arjun27** [comment]
Thanks @Kogam22 and @SinisterRectus. Looks like the token access is disabled, and we will need to find an alternative here. We have been investigating using RPC API (#266), but since it is in private beta for most features (except Rich Presence), we are hitting a roadblock. Let me think of alternatives for this and get back to you.

**Comment by crock** [comment]
Perhaps the only solution at this time is to use bot tokens instead of user tokens. I know that would make the extension way less useful for Discord users as the bot would have to be installed on each server they are in, but it's an option.

**Comment by Dev-Osmium** [comment]
Couldn't you also try and make an OAuth application (at least to read the messages for now)

**Comment by efskap** [comment]
This method still works!!
https://github.com/Tyrrrz/DiscordChatExporter/issues/76#issuecomment-410067054
(tl;dr: inspect network requests in dev tools and grab the token from the `authorization` header)

With this, the extension works great, thank you :)

**Comment by lukaskleinhaneveld** [comment]
> This method still works!!
> [Tyrrrz/DiscordChatExporter#76 (comment)](https://github.com/Tyrrrz/DiscordChatExporter/issues/76#issuecomment-410067054)
> (tl;dr: inspect network requests in dev tools and grab the token from the `authorization` header)
> 
> With this, the extension works great, thank you :)

I thought this WAS the way to get the auth token? hahaha

**Comment by efskap** [comment]
Well no, the docs still instruct the user to get the token from `localStorage.token` at the dev console.
No mention of network request inspection.

**Comment by arjun27** [comment]
Closing for now. The docs call out that discord integration is unofficial and not recommended

**Comment by balefireblaze** [comment]
Ctrl + Shift + I -> Network -> Request Method: POST(message) -> authorization
![image](https://user-images.githubusercontent.com/42090761/72439297-b5fcae00-37b7-11ea-903b-d1da8bb45ee6.png)
