### ISSUE TITLE
Live Share Chat Channel Not Working

### ISSUE THREAD

**Issue by joshuaballas** [vsls-contrib/chat#316]
I am having an issue getting the Chat Channel to work during a Live Share. It just says "Message Undefined" and it appears to send, but no one ever receives the message. Also when you hit Enter, it just goes to a new line and you have to back space back to the last character for it to attempt to send again.

We are on v.0.11.0.

I'm going to try to upload a picture of the developer console. Currently can't do that at work since they block this traffic.

**Comment by RockGuitarist1** [comment]
![08fa9ace-d1ec-4198-bc37-ea011014cda6](https://user-images.githubusercontent.com/17985542/52487779-5ef45f00-2b8c-11e9-8231-edd51c66bac0.png)

**Comment by arjun27** [comment]
Potentially related: https://twitter.com/Randy_Terros/status/1095380653091233793

**Comment by arjun27** [comment]
This should be fixed in 0.13.0. Please give it a shot and let me know if it works for you @RockGuitarist1

**Comment by RockGuitarist1** [comment]
Ok, so it looks like there was progress. As the host, this error is gon, but for anyone who has joined my session, the message box still says Undefined and they cannot send messages.

Host Image:
![Host Image](https://user-images.githubusercontent.com/17985542/56167339-f1a6e500-5fa5-11e9-9b25-d9fe391a0c0c.PNG)

Attendee Console Image:
![Attendee Console Image](https://user-images.githubusercontent.com/17985542/56167358-fb304d00-5fa5-11e9-99f6-c8402c9dc45f.png)

**Comment by arjun27** [comment]
Thanks for reporting this @RockGuitarist1. Unfortunately the console logs don't have any logs from the chat extension. Is it possible for you to share a screenshot of the console on the guest's side when they try to send a new message?

**Comment by RockGuitarist1** [comment]
We'll try it tomorrow but I am almost positive this image was taken after messages were attempted to be sent since it was during the last seconds before I left.

**Comment by arjun27** [comment]
Related to #407
