### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by ghost** [vsls-contrib/chat#336]
Sign in with slack failed: access_denied

- Extension Version: 0.12.0
- OS Version: Windows_NT x64 10.0.17763
- VSCode version: 1.31.1

**Comment by damiangreen** [comment]
Also getting this
- Extension version: Latest
- VS Code version:1.3.1

**Comment by arjun27** [comment]
Please see https://github.com/vsls-contrib/chat/blob/master/docs/SLACK.md
