### ISSUE TITLE
[vscode] Sign in with slack failed: code_already_used

### ISSUE THREAD

**Issue by mickmill54** [vsls-contrib/chat#339]
Sign in with slack failed: code_already_used

- Extension Version: 0.12.0
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.31.1

**Comment by arjun27** [comment]
Hey @mickmill54. Were you trying to manually configure the code? Or was this the auto-redirect to open VS Code?

**Comment by mickmill54** [comment]
A super irritating auto-redirect from VS Code caused by the Atlassian Jira Add-in that does not work with SSO (SAML 2.0) connections.  I uninstalled it.


Thanks for checking.  At first I thought I had some sort of security issue.

Mick Miller
216.272.5669
mick@mickmill.com

**Comment by arjun27** [comment]
Did it work for you then?

**Comment by mickmill54** [comment]
Uninstalled it.  That worked 👌

I never got SSO to work


Sent from my mobile device
1 (216) 272-5669
Mick Miller

On Mar 6, 2019, at 10:16 PM, Arjun Attam <notifications@github.com<mailto:notifications@github.com>> wrote:


Did it work for you then?

**Comment by arjun27** [comment]
Interesting. There are few other issues with the same problem that haven’t been able to repro. Perhaps the Jira extension was causing an issue for them too.

**Comment by mickmill54** [comment]
Well Atlassian send an email blast a week ago announcing the addin.

The o auth page pop ups errors stopped after I uninstalled it

https://community.atlassian.com/t5/Jira-articles/Try-Atlassian-for-VSCode-the-new-Jira-Software-and-Bitbucket/ba-p/1017882


Sent from my mobile device
1 (216) 272-5669
Mick Miller

On Mar 6, 2019, at 10:21 PM, Arjun Attam <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting. There are few other issues with the same problem that haven’t been able to repro. Perhaps the Jira extension was causing an issue for them too.

**Comment by arjun27** [comment]
Follow #414 for fix, closing as duplicate
