### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by YangChuanMakeSense** [vsls-contrib/chat#352]
Error: The user name or passphrase you entered is not correct.

- Extension Version: 0.12.0
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.32.3

When I input the access token, the error message pop up at the right foot location. After I search though all the issue about the error on the github project vscode-chat, nothing seems to work fine a little.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/27852105/54891931-552f7c80-4eea-11e9-99a5-4f13e06fdd20.png">

**Comment by YangChuanMakeSense** [comment]
And after I restart vscode, nothing changes.

**Comment by arjun27** [comment]
Follow #325 for fix. Closing as duplicate
