### ISSUE TITLE
Discord Icon disappear after clicking on it

### ISSUE THREAD

**Issue by saileshkush95** [vsls-contrib/chat#353]
When I click on Discord icon for adding it, nothings is happening. Only icon get disappear

**Comment by arjun27** [comment]
Thanks for reporting @saileshkush95, are you able to open the chat view with the "Chat: Open" or "Chat: Change Channel" commands?

**Comment by saileshkush95** [comment]
Yes, but only for slack. "Show Discord" is also not working

**Comment by arjun27** [comment]
Thanks for sharing. This might be due to an invalid Discord token. Have you tried changing the token by any chance?
