### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by BlaziusMaximus** [vsls-contrib/chat#367]
Error: Couldn't create item: The secret was transferred or encrypted in an invalid way.

- Extension Version: 0.13.0
- OS Version: Linux x64 4.15.0-47-generic
- VSCode version: 1.33.1

**Comment by arjun27** [comment]
Thanks for sharing @BlaziusMaximus. Can you tell me which Linux distro you use?

**Comment by arjun27** [comment]
Follow fix in #325
