### ISSUE TITLE
[vscode] Sign in with slack failed: access_denied

### ISSUE THREAD

**Issue by abdallah-ali-abdallah** [vsls-contrib/chat#399]
Sign in with slack failed: access_denied%0A%0A- Extension Version: 0.15.5%0A- OS Version: Linux x64 4.15.0-52-generic%0A- VSCode version: 1.35.0

**Comment by arjun27** [comment]
Please see https://github.com/vsls-contrib/chat/blob/master/docs/SLACK.md
