### ISSUE TITLE
[vscode] Unable to access keychain

### ISSUE THREAD

**Issue by tagazok** [vsls-contrib/chat#400]
Error: Unknown or unsupported transport 'disabled' for address 'disabled:'%0A%0A- Extension Version: 0.15.5%0A- OS Version: Linux x64 4.19.26-03278-g71dc68f9c9d0%0A- VSCode version: 1.35.1

On ChromeOS, I can´t  add the access tocken

**Comment by arjun27** [comment]
Follow fix in #325
