### ISSUE TITLE
Name of person displayed as hash and other instabilities

### ISSUE THREAD

**Issue by ghazpar** [vsls-contrib/chat#466]
I am on MacOS Mojave 10.14.16 using VS Code 1.43.1 with Live Share Pack 0.3.4 (Live Share Chat 0.33.0).

When I start a live share, sometimes the chat tab does not open at all. Sometimes it opens but remains blank. It then seems to be stuck waiting for something. And sometimes it opens normally and I can start typing. Anybody seen this behavior before?

When it opens but remains blank, I tried to close the tab and then click "Chat channel" to open it again. But usually, it either opens blank again or doesn't open at all.

It happens when I start a live share, and it also happens when I join a live share. Some days it seems to mostly work, and somedays it never works.

I've never received any error message from the chat.

So that is the first problem, the most severe one. The second problem is the following...

When it does work, I can always see my name in the chat, for all of my posts, but most of the time I don't see the names of the other participant's posts, what I see instead is a user specific hash. Sometimes, I dont even see this hash, all I see in that case is the time of the post. But sometimes, I can see the name of the poster. Am I the only one to experience such erratic behavior?

Moreover, I always see the names of the participants in the LiveShare left side-bar. So the problem appears to be within the chat itself. 

When I join a share, I usually see the name of the share host inside the chat, but the names of the other posters are hashes. Today we made several tests and it happened to me and both other participants. One was on Windows and the other on Linux. So it seems that there is definitely a problem with the chat, it is not just with my setup. But it may be more severe on MacOS, since the other participants told me that their chat always opens normally. 

BTW the audio chat is also intermittent for me, but not for my two coworkers on Windows and Linux. Perhaps it is related. I will file a separate bug report for the audio chat, but here is a summary. On the left side-bar it tells me that I am connected to the audio chat, I can hear the others, but they can't hear me. And then suddenly, today, my machine asked me to allow Electron to access my microphone!? And then, it started to work very well, but not for every session. Again there is something flaky. When it doesn't work, I close the session and have to try again until the others can hear me. 

Before today, I was never asked to allow Electron to access my microphone. I checked the privacy settings and they now say that Electron is allowed to access the builtin microphone. I don't know if this setting was on before, but I have no microphone issues with any other app.

Hope someone can fix this because I really need this feature to be stable and dead simple for my students to use.

Best regards, 
MP

**Comment by arjun27** [comment]
Thanks for taking the time to report this @ghazpar. The Live Share integration for chat definitely emerged as a key scenario for this extension (which focuses on just chat), and we have aligned on a path where chat becomes a first class feature of Live Share core. You will see activity on moving chat into the Live Share extension, which would fix these coordination issues between the two extensions.

**Comment by ghazpar** [comment]
Thanks for the quick response. So @arjun27 you are saying that these issues are known, but can't be fixed without integration into the live share core? Any idea about a timeframe for that?

**Comment by KerberosMorphy** [comment]
Tested for MacOS Catalina 10.15.3 using VS Code 1.43.1 with Live Share Pack 0.3.4, Live Share Chat 0.33.0, Live Share Audio 0.1.80, Live Share Extension Pack 0.3.4.

I can confirm for the Microphone Permission, MacOS doesn't trigger the permission for Electron/VS Code and one doesn't not simply give permission manually on a MacOS.

I don't have the knowledge to propose a fix, but apparently for Electron there's a way to get the media access status and/or request it, it's necessary since Mojave 10.14
[Electron Ask For Media Access](https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos)

**Comment by arjun27** [comment]
Chat is now integrated in the core Live Share extension. Please file an issue if you are running into issues with the Slack integration.
