### ISSUE TITLE
Chat is not working.

### ISSUE THREAD

**Issue by ChezCoder** [vsls-contrib/chat#469]
The chat is just blank. I can type in the message box but when I hit enter, it's just blank.

I'm on a mac, so maybe you need to work on adding support for macOS?

Latest versions of VS Code and Live Chat

**Comment by arjun27** [comment]
Thanks for reporting, and apologies for the late response. Chat is now integrated in the core Live Share extension. Please file an issue if you are running into issues with the Slack integration.
