### ISSUE TITLE
[vscode] Sign in with Slack failed: code_already_used

### ISSUE THREAD

**Issue by monsieurmeemy** [vsls-contrib/chat#76]
Sign in with Slack failed: code_already_used

- Extension Version: 0.5.7
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.26.1

**Comment by arjun27** [comment]
Thanks for reporting this @monsieurmeemy. The `code_alreeady_used` error generally happens if the web page has been reloaded after a successful auth on Slack. Is this happening consistently for you? If so, it must be a bug

**Comment by monsieurmeemy** [comment]
Can't sign into slack even after authorizing on browser

**Comment by arjun27** [comment]
Follow #414 for fix, closing as duplicate
