### ISSUE TITLE
Add customize settings

### ISSUE THREAD

**Issue by mittalyashu** [vsls-contrib/chat#80]
## Font

* Change font size
* Change font family

![image](https://user-images.githubusercontent.com/29014463/44901017-dee7e480-ad23-11e8-9d3a-834220e839c4.png)

## Side panel

* Show and hide sections _(maybe I don't want to see the group section)_

![image](https://user-images.githubusercontent.com/29014463/44901079-063eb180-ad24-11e8-8caf-0f7f337e1632.png)

**Comment by arjun27** [comment]
thanks @mittalyashu. would love to get your thoughts on these:

- I'm thinking of auto-hiding the "groups" section if that is empty. would that solve this for you?
- the font size is picked up from the `editor.fontSize` configuration right now, which is the default way for users to set font sizes in vs code. correct me if I'm wrong, but I believe users would want the same font size for the editor and the slack window, and therefore we can stick with this for now.
- I'm not sure how your screenshot has two different font faces for the message input box and the received messages. is there any font related setting on your setup that could be causing this issue?

**Comment by mittalyashu** [comment]
> I'm thinking of auto-hiding the "groups" section if that is empty. would that solve this for you?

Auto-hiding sections is not a good idea.

> the font size is picked up from the `editor.fontSize` configuration right now, which is the default way for users to set font sizes in vs code. correct me if I'm wrong, but I believe users would want the same font size for the editor and the slack window, and therefore we can stick with this for now.

Add the option where we can customize the font size for the chat.

> I'm not sure how your screenshot has two different font faces for the message input box and the received messages. is there any font related setting on your setup that could be causing this issue?

Not sure about that.

**Comment by arjun27** [comment]
Closing this as wontfix
